import type { Book } from "@/components/book-list"

export const mockBooks: Book[] = [
  {
    id: "book-1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description:
      "Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
    price: 12.99,
    condition: "good",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-1",
      name: "John Doe",
    },
    listingType: "sell",
    createdAt: "2023-05-15T10:30:00Z",
  },
  {
    id: "book-2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description:
      "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. It's the story of the Finch family and their experience with racial injustice in 1930s Alabama.",
    price: 9.99,
    condition: "very-good",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-2",
      name: "Jane Smith",
    },
    listingType: "both",
    createdAt: "2023-06-20T14:45:00Z",
  },
  {
    id: "book-3",
    title: "1984",
    author: "George Orwell",
    description:
      "A dystopian social science fiction novel that examines the consequences of totalitarianism, mass surveillance, and repressive regimentation of persons and behaviors within society.",
    price: 11.5,
    condition: "like-new",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-3",
      name: "Robert Johnson",
    },
    listingType: "sell",
    createdAt: "2023-07-05T09:15:00Z",
  },
  {
    id: "book-4",
    title: "Dune",
    author: "Frank Herbert",
    description:
      'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.',
    price: 14.99,
    condition: "good",
    category: "Science",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-1",
      name: "John Doe",
    },
    listingType: "sell",
    createdAt: "2023-08-10T15:20:00Z",
  },
  {
    id: "book-5",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description:
      "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep.",
    price: 12.99,
    condition: "acceptable",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-4",
      name: "Emily Wilson",
    },
    listingType: "both",
    createdAt: "2023-09-05T11:45:00Z",
  },
  {
    id: "book-6",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description:
      "The story follows the main character, Elizabeth Bennet, as she deals with issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry of the British Regency.",
    price: 8.99,
    condition: "good",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-5",
      name: "Sarah Thompson",
    },
    listingType: "sell",
    createdAt: "2023-10-15T13:30:00Z",
  },
  {
    id: "book-7",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description:
      'The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school. Confused and disillusioned, Holden searches for truth and rails against the "phoniness" of the adult world.',
    price: 10.99,
    condition: "very-good",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-2",
      name: "Jane Smith",
    },
    listingType: "sell",
    createdAt: "2023-11-20T16:15:00Z",
  },
  {
    id: "book-8",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description:
      "The Alchemist follows the journey of an Andalusian shepherd boy named Santiago. Believing a recurring dream to be prophetic, he decides to travel to a Romani fortune-teller in a nearby town to discover its meaning.",
    price: 9.5,
    condition: "like-new",
    category: "Fiction",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-6",
      name: "Michael Brown",
    },
    listingType: "exchange",
    createdAt: "2023-12-05T10:00:00Z",
  },
  {
    id: "book-9",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description:
      "A landmark volume in science writing by one of the great minds of our time, Stephen Hawking's book explores such profound questions as: How did the universe begin—and what made its start possible?",
    price: 15.99,
    condition: "good",
    category: "Science",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-3",
      name: "Robert Johnson",
    },
    listingType: "sell",
    createdAt: "2024-01-10T08:30:00Z",
  },
  {
    id: "book-10",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description:
      "In Sapiens, Dr. Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical breakthroughs of the Cognitive, Agricultural and Scientific Revolutions.",
    price: 14.5,
    condition: "very-good",
    category: "History",
    image: "/placeholder.svg?height=300&width=200",
    seller: {
      id: "user-5",
      name: "Sarah Thompson",
    },
    listingType: "both",
    createdAt: "2024-02-15T11:20:00Z",
  },
]

export const mockCharities = [
  {
    id: "charity-1",
    name: "Books for Schools Foundation",
    description:
      "We provide textbooks, notebooks, and school supplies to underprivileged primary schools to support early education.",
    category: "Education",
    location: "New York, NY",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Textbooks", "Notebooks", "Pencils", "Educational Games"],
    email: "contact@booksforschools.org",
    website: "https://example.com/booksforschools",
    phone: "212-555-0123",
  },
  {
    id: "charity-2",
    name: "Digital Literacy Initiative",
    description:
      "Providing refurbished laptops and technology books to university students from low-income backgrounds.",
    category: "Technology",
    location: "San Francisco, CA",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Laptops", "Computer Science Books", "Programming Guides", "Technical Manuals"],
    email: "help@digitalliteracy.org",
    website: "https://example.com/digitalliteracy",
    phone: "415-555-0189",
  },
  {
    id: "charity-3",
    name: "Community Reading Project",
    description:
      "Building community libraries in underserved neighborhoods to promote literacy and provide access to books for all ages.",
    category: "Literacy",
    location: "Chicago, IL",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Fiction Books", "Children's Books", "Young Adult Books", "Reference Materials"],
    email: "info@communityreading.org",
    website: "https://example.com/communityreading",
    phone: "312-555-0156",
  },
  {
    id: "charity-4",
    name: "Global Education Access",
    description:
      "Shipping educational materials to schools in developing countries to support literacy and education worldwide.",
    category: "International",
    location: "Washington, DC",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Textbooks", "Educational Materials", "Children's Books", "Dictionaries"],
    email: "support@globaleducation.org",
    website: "https://example.com/globaleducation",
    phone: "202-555-0178",
  },
  {
    id: "charity-5",
    name: "Senior Reading Connection",
    description:
      "Providing large-print books and audiobooks to senior centers and nursing homes to keep elderly minds active and engaged.",
    category: "Elderly Care",
    location: "Miami, FL",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Large-Print Books", "Audiobooks", "Classic Literature", "Magazines"],
    email: "contact@seniorreading.org",
    website: "https://example.com/seniorreading",
    phone: "305-555-0134",
  },
  {
    id: "charity-6",
    name: "Prison Library Project",
    description:
      "Donating books to prison libraries to support education, rehabilitation, and personal growth for incarcerated individuals.",
    category: "Social Justice",
    location: "Los Angeles, CA",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Fiction", "Self-Help Books", "Educational Materials", "Legal Resources"],
    email: "donate@prisonlibrary.org",
    website: "https://example.com/prisonlibrary",
    phone: "213-555-0167",
  },
  {
    id: "charity-7",
    name: "Children's Book Bank",
    description:
      "Collecting and distributing children's books to families in need to promote early literacy and a love of reading.",
    category: "Children",
    location: "Portland, OR",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Picture Books", "Early Readers", "Chapter Books", "Educational Toys"],
    email: "info@childrensbookbank.org",
    website: "https://example.com/childrensbookbank",
    phone: "503-555-0145",
  },
  {
    id: "charity-8",
    name: "Medical Literature Exchange",
    description:
      "Providing up-to-date medical textbooks and journals to healthcare facilities in underserved areas and developing countries.",
    category: "Healthcare",
    location: "Boston, MA",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Medical Textbooks", "Medical Journals", "Anatomy Books", "Healthcare Guides"],
    email: "donate@medicalliterature.org",
    website: "https://example.com/medicalliterature",
    phone: "617-555-0123",
  },
  {
    id: "charity-9",
    name: "Veterans' Reading Program",
    description:
      "Supporting veterans through book donations, reading groups, and literacy programs to aid in reintegration and healing.",
    category: "Veterans",
    location: "Austin, TX",
    image: "/placeholder.svg?height=200&width=400",
    needs: ["Fiction", "History Books", "Self-Help", "Career Guides"],
    email: "support@veteransreading.org",
    website: "https://example.com/veteransreading",
    phone: "512-555-0189",
  },
]
